### ISSUE TITLE
catalina使用的类被增强后，无法引用到由oneagent ClassLoaderHandler加载的工具类

### ISSUE THREAD

**Issue by lastboy1228** [alibaba/one-java-agent#49]
一开始测试注入spring的AsyncExecutionAspectSupport类时，plugin lib里的工具类AsyncTaskInfo能够在注入的代码执行时成功被加载；
然后测试注入java.util.concurrent.AbstractExecutorService类时，注入的代码执行时加载不到工具类AsyncTaskInfo了。

日志：
在ClassLoader_Instrument打印了loadClass的记录，可以看到工具类AsyncTaskInfo是被PluginClassLoader加载成功了的
```
 :: Spring Boot ::                (v2.6.6)

05-12 10:51:39,865  INFO [main] (StartupInfoLogger.java:55) : Starting HttpApplication using Java 1.8.0_232 on wangzp13960 with PID 33152 (E:\workspace\FinTech\MONI\dubbo.demo\dubbo.demo.alibaba.consumer\target\classes started by wangzp13 in E:\workspace\FinTech\MONI\one-java-agent-plugins)
05-12 10:51:39,891 DEBUG [main] (StartupInfoLogger.java:56) : Running with Spring Boot v2.6.6, Spring v5.3.18
05-12 10:51:39,893  INFO [main] (SpringApplication.java:640) : No active profile set, falling back to 1 default profile: "default"
ClassLoader_Instrument: AsyncExecutionAspectSupport开始被加载 -sun.misc.Launcher$AppClassLoader
ClassLoader_Instrument: AsyncExecutionAspectSupport准备被one agent classloader spy加载
ClassLoader_Instrument: AsyncExecutionAspectSupport没有被one agent classloader spy加载到
ClassLoader_Instrument: AsyncExecutionAspectSupport被ClassLoader加载到 -sun.misc.Launcher$AppClassLoader
ClassLoader_Instrument: AsyncTaskInfo开始被加载 -sun.misc.Launcher$AppClassLoader
ClassLoader_Instrument: AsyncTaskInfo准备被one agent classloader spy加载
ClassLoader_Instrument: AsyncTaskInfo开始被加载 -com.alibaba.oneagent.plugin.classloader.PluginClassLoader
ClassLoader_Instrument: AsyncTaskInfo被ClassLoader加载到 -com.alibaba.oneagent.plugin.classloader.PluginClassLoader
ClassLoader_Instrument: AsyncTaskInfo被one agent classloader spy加载到
ClassLoader_Instrument: AbstractExecutorService开始被加载 - sun.misc.Launcher$AppClassLoader
ClassLoader_Instrument: AbstractExecutorService准备被one agent classloader spy加载
ClassLoader_Instrument: AbstractExecutorService没有被one agent classloader spy加载到
ClassLoader_Instrument: AbstractExecutorService被ClassLoader加载到 - sun.misc.Launcher$AppClassLoader
ThreadPoolExecutorInstrument：开始检查classloader能否加载到AsyncTaskInfo - sun.misc.Launcher$AppClassLoader
ThreadPoolExecutorInstrument：classloader加载不到AsyncTaskInfo - sun.misc.Launcher$AppClassLoader
ThreadPoolExecutorInstrument：开始检查classloader能否加载到AsyncTaskInfo - sun.misc.Launcher$AppClassLoader
ThreadPoolExecutorInstrument：classloader加载不到AsyncTaskInfo - sun.misc.Launcher$AppClassLoader
java.lang.ClassNotFoundException: com/xxx/monitor/oneagent/common/async/AsyncTaskInfo
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:19)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:478)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:211)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at com.xxx.jr.dubbo.demo.alibaba.consumer.HttpApplication.main(HttpApplication.java:43)
java.lang.ClassNotFoundException: com/xxx/monitor/oneagent/common/async/AsyncTaskInfo
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:19)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:478)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:211)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at com.xxx.dubbo.demo.alibaba.consumer.HttpApplication.main(HttpApplication.java:43)
```

**Comment by hengyunabc** [comment]
没看懂，最好提交一个可重现的demo。

**Comment by lastboy1228** [comment]
忽略吧，不应该去注入jdk里的类：java.util.concurrent.AbstractExecutorService
